# helm/django-pg-app/values.yaml
image:
  repository: ghcr.io/3452818/django-pg-k8s-deploy
  tag: latest
  pullPolicy: IfNotPresent

app:
  port: 3003
  env:
    DB_HOST: django-pg-app-postgresql
    DB_NAME: tutorial-dev
    DB_USER: vinhle
    DB_PASS: password

postgres:
  enabled: true
  image:
    repository: postgres
    tag: 13-alpine
  env:
    POSTGRES_DB: tutorial-dev
    POSTGRES_USER: vinhle
    POSTGRES_PASSWORD: password
  persistence:
    enabled: false
    size: 1Gi
  service:
    port: 5432